### ISSUE TITLE
Preload every visible link

### ISSUE THREAD

**Issue by grahamperrin** [simonfrey/faster-pageload-web-extensions#1]
Re: https://instant.page/changelog and https://instant.page/v3

> … option to preload every visible link …

Please, might you add this option? In a preferences page for the extension.

I'll be interested to see its effect with desktop browsers (Waterfox Classic 2019.10, Firefox 71.0).

**Comment by simonfrey** [comment]
Interesting feature. Will be added soon.
More info on its config: https://instant.page/intensity#viewport
When activated we need to add `data-instant-intensity="viewport"` as attribute to the `<body>` tag.

**Comment by simonfrey** [comment]
Added the preload of all links in viewport to addon. Default it is on. Can be disabled via the options page

**Comment by grahamperrin** [comment]
> Default it is on. 

With respect, 

-1

– the feature is welcome but defaulting to on may be unexpectedly contentious, from privacy/tracking perspectives. 

https://github.com/simonfrey/faster-pageload-web-extensions/commit/53bb4ef9dab821e4de507562aa5ef82f393761d6#diff-9ac008c7e2c4d3a6421cdf1d4faec43aR18

**Comment by simonfrey** [comment]
You are right about that. Changed it to not being default activated.
