### ISSUE TITLE
warning pop-up blocker

### ISSUE THREAD

**Issue by gabri25ele** [simonfrey/faster-pageload-web-extensions#11]
with the latest update I always have the warning on firefox of a pop-up blocker on each link to a new window.

**Comment by simonfrey** [comment]
Yes is a problem with https://instant.page/ v5
I reverted the plugin back to the version v3 of the script and will further investigate the issue. 

Thanks for reporting!

**Comment by simonfrey** [comment]
v5 is still buggy. Will stay on the v3.0.0 as long as no particularly interesting features are introduced by newer versions.
