### ISSUE TITLE
Blacklist a broken website?

### ISSUE THREAD

**Issue by CactiChameleon9** [simonfrey/faster-pageload-web-extensions#12]
Preload every visible link breaks this site (login weird behaviour): https://snakify.org/en/, is it possible to add a blacklist feature so certain websites's preloading can be turned off?

**Comment by simonfrey** [comment]
Nice idea to add a blacklist feature. Is quite some work to have that in a usable way.

**Comment by CactiChameleon9** [comment]
I am not rubbish at coding - could you briefly explain which file does what and I could have a small go?

**Comment by simonfrey** [comment]
Would be awesome if you could give it a go.

IMO there are four important files for this task: 
- [Options page](https://github.com/simonfrey/faster-pageload-web-extensions/blob/master/options.html) where you can add a textarea containing the blacklisted sites
- [options.js](https://github.com/simonfrey/faster-pageload-web-extensions/blob/master/js/options.js#L4-L12) for saving the values of the options page into local storage
- [instant_page.min.js](https://github.com/simonfrey/faster-pageload-web-extensions/blob/master/js/instant_page.min.js#L7) & [lazy_images.js](https://github.com/simonfrey/faster-pageload-web-extensions/blob/master/js/lazy_images.js#L23) where you need to load the values from the local store and check if the current page is on that list.

**Comment by CactiChameleon9** [comment]
Thanks for the info. I have never used javascript before - but I can try. I assume I should fork and then do a pull request once done?

**Comment by CactiChameleon9** [comment]
I have somehow managed it... so yay :D 

The pull request is here:
https://github.com/simonfrey/faster-pageload-web-extensions/pull/13

**Comment by simonfrey** [comment]
Fixed with #13
