### ISSUE TITLE
Toolbar button (browser action)

### ISSUE THREAD

**Issue by grahamperrin** [simonfrey/faster-pageload-web-extensions#2]
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/user_interface/Browser_action

It'll be smart for a button to (at least) simply toggle the effects of the extension off/on. 

Re: #1 I should expect use cases where it's desirable to simply, quickly switch off before proceeding to a page where preloading is inappropriate. 

### Icon suggestion

A human nose, viewed from the side. 

Not this one in particular: 

![image](https://user-images.githubusercontent.com/192271/70454969-4e11c400-1aa3-11ea-8d41-ae205a5b6220.png)

– but that's the idea. 

(Image source: <https://search.creativecommons.org/photos/379e5417-280f-49fc-ac7f-f2f15a6d891d>)

TIA

**Comment by simonfrey** [comment]
Added toolbar button with version 1.6.5
