### ISSUE TITLE
☑ Preload every visible link – maybe not working as expected

### ISSUE THREAD

**Issue by grahamperrin** [simonfrey/faster-pageload-web-extensions#3]
Hi

1. about:addons
2. view preferences for the extension
3. ☑ Preload every visible link 
4. https://instant.page/tech
5. refrain from pointing at any of the links to the right
6. <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>E</kbd> (network console)
7. <kbd>Control</kbd>-<kbd>F5</kbd> (reload, override cache)

### Expected

8. preloading

### Actual result

8. unless I'm missing something, no preloading

### <strike>Workaround </strike>Next steps

9. new tab
10. about:config
11. prefetch
12. override relevant defaults
13. bring the **Technical details — instant.page** tab to front
14. <kbd>Control</kbd>-<kbd>F5</kbd>
15. begin pointing at links
16. observe preloading, when pointing at a link

**Comment by simonfrey** [comment]
What are "12. relevant defaults" I found more than 5. Which on did you change?

Maybe this is an overall problem with FF as they do not allow prefetching as intense as chrome.
I may add a note on install to change that preferences if we can boil it down to 1 or 2 important ones.

**Comment by simonfrey** [comment]
Not sure though if that is a good idea to train users to change their "about:config" if they are asked by a plugin

**Comment by simonfrey** [comment]
Okay the problem that the viewport does not preload is fixed. I missread the documentation here. With `viewport` it only preloads on mobile. Changed it to `viewport-all` for preloading on other viewports as well =>1.5.6

**Comment by grahamperrin** [comment]
Re: https://github.com/simonfrey/faster-pageload-web-extensions/issues/3#issuecomment-563936022

![image](https://user-images.githubusercontent.com/192271/70531616-29722680-1b4d-11ea-9003-5931851a46e2.png)

`network.dns.disablePrefetchFromHTTPS` changed to `false`

`network.predictor.enable-prefetch` changed to `true`

Sorry, my careless use of the word *Workaround*. What I meant was, they were steps towards determining whether there was an issue with the extension. 

I'll revert both preferences to their defaults then test 1.5.6.

**Comment by grahamperrin** [comment]
Now working as expected, thanks. 

Nit: a click on **Save** in **Preferences** should not step away from the preferences …

**Comment by simonfrey** [comment]
With version 1.5.9 the addon displays a message on install/update to set the prefetch settings to make the instant.page script work
