### ISSUE TITLE
How is the image lazy load different from the browser's builtin image lazy load feature?

### ISSUE THREAD

**Issue by IceMan81** [simonfrey/faster-pageload-web-extensions#7]
Is there an advantage to using the extension's lazy load functionality vs the browser's built in function?

**Comment by IceMan81** [comment]
The reason I asked this was because I noticed when the lazy loading option is enabled, I find the image loading slower than when using using the browser option. So it feels like there is a difference in how the extension functions.

**Comment by simonfrey** [comment]
The extension uses the lazy loading function build into the browser if available(Y)

**Comment by IceMan81** [comment]
@simonfrey the behavior seems to be different. Lazy loading is enabled by default in FF 75. If I enable the lazy loading option in the extension, then image loading is quite delayed. If I leave it unchecked, and the lazy loading FF config is enabled, then the images load a lot faster.

**Comment by simonfrey** [comment]
I finally got your point! There where two problems that are now solved with 1.7:
- If possible the plugin uses the native lazy loading instead of interceptor
- Image request are blocked before the lazy loading happend to not double load the images

**Comment by IceMan81** [comment]
@simonfrey Thanks, I'll try out the new version. 
How does the plugin compare with the predictive prefetching feature in FF? Sorry about all the questions, just trying to understand the plugin's intended behavior.

**Comment by simonfrey** [comment]
It actually uses the FF feature, by adding the prefetch parameter to urls. The used tech for that can found here: https://instant.page/tech

Additional to the instant.page script this extension uses lazyloading to further speed up things. Thereby the lazy loading feature of the browser is used if available, by adding the loading="lazy" parameter to the images. This helps with websites that do not have lazy loading themselves

**Comment by IceMan81** [comment]
@simonfrey Thank you for the details. If I understood correctly, the addon is adding the `loading=lazy` params even for URLs that is not taking advantage of FF's lazy loading feature.

I'm noticing an issue with the updated plugin with FF76 (Beta). 
If lazy image loading is enabled in the addon (without any change to the browser default - in my case the lazy load FF config is always enabled i.e `dom.image-lazy-loading.enabled=true`), then I notice that some images / videos do not load for some websites. I've seen issues with YouTube and some of the news websites I use. If I uncheck the lazy loading option in the addon and save and come back and refresh the page, all images load fine. 

Now, I also noticed that I cannot reproduce the issue consistently. Sometimes, if I re-enable the lazy load option in the addon and come back and open youtube I don't see any issues.

**Comment by IceMan81** [comment]
@simonfrey It seems the issue occurs when the images are thumbnails - including youtube thumbnails.
