### ISSUE TITLE
New deactivate icon

### ISSUE THREAD

**Issue by xan2622** [simonfrey/faster-pageload-web-extensions#8]
Hi.

Could it be possible to have a more visible PNG deactivate icon?

For example, this one: 

![launch_96_deactivate](https://user-images.githubusercontent.com/1732773/78423933-27872280-766a-11ea-9552-4f9513601617.png)

It would make the icon (and the status of the Faster Pageload button) more visible, especially on 4K screens.

**Comment by simonfrey** [comment]
Solved by using a svg in version 1.7.2

**Comment by xan2622** [comment]
Hi. 

It's nice to see that a SVG file is used but my comment was about to have a more noticeable icon. 
I am sorry if I wasn't clear enough.

For example, the new *rocket_deactivate.svg* file still has the "engine thrust flame".

The only difference between the two icons is the fact that the "deactivate" one is grey (and this might not be enough for color-blind people to distinguish between the two icons)

Could you consider using this SVG icon instead?

![icon_preview](https://user-images.githubusercontent.com/1732773/78676804-39c1c480-78e7-11ea-95c7-553ef069e614.png)

The SVG deactivate icon: [rocket_deactivate.zip](https://github.com/simonfrey/faster-pageload-web-extensions/files/4444809/rocket_deactivate.zip)

**Comment by simonfrey** [comment]
Ah now I got you. Nice idea. Added it in 1.7.5.1
